personnage = [
    {
        id: "0",
        title: "Commandant Madine",
        image: "Ressource/Image/Personnages/CommandantMadine.jpg",
        categorie: "Militaire et Guerrier",
        espece: "Humain",
        sexe: "Masculin",
        statut: "Commandant",
        corps: "Cassius Madine était le commandant des forces républicaines déployées sur Balmorra en -3642 dans le cadre du soutien à la résistance locale contre l'occupation impériale.Depuis la base avancée de Vermineville, il mena diverses opérations pour repousser l'Empire Sith de Balmorra avec l'aide de puissants combattants alliés, jusqu'au jour où il découvrit l'existence du Barrager, une super arme conçue par des scientifiques Balmorréens. Avec l'aide des scientifiques liés au projet, il parvint à mettre la main dessus mais devint obsédé à l'idée de l'utiliser contre les impériaux, malgré les dommages collatéraux que cela pouvait causer. Le destin de Balmorra reposa alors entre les mains de ses agents qui étaient responsables de cette découverte.",
    },
    {
        id: "1",
        title: "Archiban Kimble",
        image: "Ressource/Image/Personnages/Doc.jpg",
        categorie: "Docteur",
        espece: "Humain",
        sexe: "Masculin",
        statut: "Medecin Militaire",
        corps: "Médecin brillant et voyageur intrépide à l'égo surdimensionné, Doc est toujours en quête d'une nouvelle aventure à vivre. Né sur Ralltiir, dans les Mondes du Noyau, il s'est toujours imaginé en héros, bravant les pires difficultés et surmontant tous les obstacles, bien souvent pour secourir une charmante demoiselle en détresse. C'est ainsi qu'il concevait sa vie, et quand on lui offrit d'étudier la médecine dans l'une des académies les plus prestigieuses de la République, Doc sauta dans la première navette à destination de Coruscant. Figurant parmi l'élite de sa promotion, le docteur Kimble aurait pu rejoindre l'hôpital ou la clinique de son choix. Mais, au lieu d'opter pour la solution de facilité, Doc se mit à proposer ses services dans bon nombre des zones les plus périlleuses de la galaxie. Réussissant toujours à tirer son épingle du jeu, Doc devint par la même occasion une gâchette des plus rapides. Son insatiable soif d'aventures côtoie un profond désir de soigner ceux qui souffrent et de venir en aide aux plus faibles. La seule différence entre Doc et ses confrères réside dans le fait qu'il n'hésite pas à se mêler aux criminels, aux gangs de fonceurs et aux forceurs de blocus pour aider ceux qui ont besoin de lui.",
    },
    {
        id: "2",
        title: "Otak'or Meln",
        image: "Ressource/Image/Personnages/DocteurMeln.jpg",
        categorie: "Docteur",
        espece: "Twi'lek",
        sexe: "Masculin",
        statut: "Medecin",
        corps: "Otak'or Meln était un médecin Twi'lek de Balmorra qui a conçu la super-arme Barrager avec son collègue le docteur Ortis pendant la guerre froide. Après que l' Empire Sith reconstitué ait pris le contrôle de Balmorra, Meln et Ortis furent jetés dans Gorinth Brig , tandis que le Barrager resta inachevé. En 3642 av.BY, ils furent sauvés de l'emprisonnement par un citoyen de la République et apportèrent leur aide pour remettre le Barrager désormais complet entre les mains de la République.",
    },
    {
        id: "3",
        title: "Docteur Ortis",
        image: "Ressource/Image/Personnages/DocteurOrtis.jpg",
        categorie: "Docteur",
        espece: "Humain ",
        sexe: "Masculin",
        statut: "Medecin",
        corps: "Ortis était un médecin humain de Balmorra qui a conçu la super-arme Barrager avec son collègue le docteur Otak'or Meln pendant la guerre froide. Après que l' Empire Sith ait pris le contrôle de Balmorra, Meln et Ortis furent jetés dans Gorinth Brig , tandis que le Barrager resta inachevé. En 3642 av.BY, ils furent sauvés de l'emprisonnement par un citoyen de la République et apportèrent leur aide pour remettre le Barrager désormais complet entre les mains de la République .",
    },
    {
        id: "4",
        title: "Docteur Carciri",
        image: "Ressource/Image/Personnages/DocteurCarsiri.jpg",
        categorie: "Docteur",
        espece: "Humain ",
        sexe: "Masculin",
        statut: "Medecin",
        corps: "Carsiri était un médecin humain qui a vécu pendant la guerre galactique. Sur Balmorra, il fut contraint de travailler sur l' arme Barrager pour l' Empire Sith reconstitué, mais fit défection vers la République Galactiqueà la première occasion. Il a aidé Cassius Madine à localiser l'arme et, après la mort de son surveillant Dark Minax, il a supposé que la République détruirait l'arme. Il fut déçu lorsque Madine voulut le garder, car le Barrager pourrait endommager la planète entière s'il était utilisé.",
    },
    {
        id: "5",
        title: "Grand Marshal Cheketta",
        image: "Ressource/Image/Personnages/Cheketta.jpg",
        categorie: "Militaire et Guerrier",
        espece: "Humain ",
        sexe: "Masculin",
        statut: "Grand Marshall",
        corps: "Cheketta était un ancien Grand Maréchal humain qui a servi dans l' armée de la République. Il fut envoyé à Balmorra afin de guider la résistance balmorréenne dans sa lutte contre la résurgence de l'Empire Sith pendant la Guerre froide. C'était un commandant talentueux , mais à la fin, il fut quand même vaincu par un puissant individu aligné sur l'Empire.",
    },
    {
        id: "6",
        title: "Maître Warren",
        image: "Ressource/Image/Personnages/Warren.jpg",
        categorie: "Jedi",
        espece: "Humain",
        sexe: "Masculin",
        statut: "Maître ",
        corps: "Homme humain né plusieurs décennies avant 3681 av.BY , Warren Sedoru, sensible à la Force, a été formé comme Jedi et est rapidement devenu l'un des chevaliers Jedi les plus acclamés de l' Ordre Jedi. Lorsque l' Empire Sith renaissant reconquit son monde sacré lors de la bataille de Korriban et commença la Grande Guerre Galactique avec la République Galactique , Sedoru fut l'un des premiers Jedi à mener des contre-attaques contre les forces impériales. Il a remporté plusieurs premières victoires contre les Sith , combattant dans des dizaines de batailles à travers la galaxie sur des mondes tels que Yavin 4 et Alderaan, mais a été grièvement blessé lors de plusieurs de ces conflits. Alors qu'il a survécu sans cybernétique ni prothèses, le lien de Sedoru avec la Force a commencé à diminuer, et lorsque le Traité de Coruscant a mis fin à la guerre en 3653 av.BY, il s'est consacré à la paix. Abandonnant le rang de Chevalier Jedi, il devint Padawan du Maître Jedi Tol Braga .Sedoru fut envoyé à Balmorra pour obtenir un dispositif de camouflage, peut-être créé par les Gree ou les Rakata, la même technologie utilisée pour cacher la forteresse de l'Empereur. Mais l'appareil se trouvait dans l' usine d'armes de Balmorran , aujourd'hui un bastion impérial, ils auraient donc besoin de l'aide de la résistance locale.",
    },
    {
        id: "7",
        title: "Jace Malcom",
        image: "Ressource/Image/Personnages/JaceMalcom.jpg",
        categorie: "Militaire et Guerrier",
        espece: "Humain",
        sexe: "Masculin",
        statut: "Général",
        corps: "Jace Malcom était un soldat humain de la République , qui a servi dans la Division des Forces Spéciales de l' Armée de la République pendant la Grande Guerre Galactique et la Guerre Froide, et en tant que Commandant Suprême de l'armée pendant la Guerre Galactique . Malcom a grandi sur le monde Mid Rim de Barcaria , mais l'a quitté très jeune pour rejoindre les forces de défense de la République Galactique.En 3681 av.BY , il servait comme caporal à bord d'une station spatiale Jedi en orbite au -dessus de Korriban . Cette année-là, l' Empire Sith reconstitué retourna dans l'espace connu pour récupérer son territoire perdu et se venger de la République. Au cours des premiers jours de la Grande Guerre Galactique qui s'ensuivit , l'Empire lança une attaque massive contre les forces Jedi et de la République à Korriban dans le but de reprendre le monde qui était autrefois leur capitale sacrée . Malcom a été pris dans la bataille, mais a réussi à échapper à l'assaut aux côtés du Jedi Padawan Satele Shan et du contrebandier incarcéré , le capitaine Nico Okarr. La guerre s'est poursuivie pendant près de trois décennies, période pendant laquelle Malcom a été intronisé dans les forces spéciales de l'armée de la République et s'est vu confier le commandement de l' unité d'infanterie d'élite 326. Sous la direction de Malcom, l'unité a effectué des raids très risqués en territoire ennemi et a gagné le surnom de « Havoc Squad ».Au plus fort de la guerre, l' escouade était stationnée sur le Monde Noyau d' Aldérande tandis que le gros de la Marine de la République se trouvait ailleurs dans la galaxie , combattant les Sith. Alors qu'il était stationné sur la planète, Malcom et ses soldats furent entraînés dans la bataille d'Alderaan , une invasion impériale massive du monde tranquille. Alors que les forces Sith dirigées par Dark Malgus ravageaient la planète, Malcom et ses camarades se sont rendus dans les forêts d'Alderaan pour mener une campagne de guérilla contre les Impériaux.\
        \"Lorsque Dark Malgus tourna son armée vers la capitale d' Alderaanian , le commandant et l'escouade du Havoc se positionnèrent pour tendre une embuscade au Seigneur Sith et stopper son avance. Dans une bataille rangée dans les forêts à l'extérieur de la capitale, l'escadron du Havoc a mis en déroute l'armée impériale et Malcom a combattu et vaincu Malgus lui-même avec l'aide du chevalier Jedi de l'époque , Satele Shan. Le leadership de Malcom pendant la bataille lui a valu, ainsi qu'à l'escouade du Chaos, un grand prestige dans toute la République et a inspiré une résilience continue contre les Sith. Cette renommée a attiré l'attention du colonel Elin Garza , avec qui Malcom a aidé à fonder une nouvelle division des forces spéciales à part entière et indépendante. À peu près à la même époque, Malcom entretenait une relation secrète avec Shan qui aboutissait finalement à une rupture tendue. Cependant, avant la mort de leur relation amoureuse, Malcom et Shan ont engendré un fils, Theron Shan . Malcom reçut plus tard une promotion au grade de colonel. Après la fin de la guerre et la mise en œuvre d'un accord de paix controversé , Malcom fut invité à retourner sur Alderaan pour superviser les efforts des combattants de la République dans la sanglante guerre civile qui avait englouti la planète. En tant que conseiller stratégique d'Alderaan pour l'armée de la République , Malcom surveillait les déploiements de troupes et les plans tactiques et maintenait l'alliance militaire entre les forces armées de la République et la noble maison Organa.",
    },
    {
        id: "8",
        title: "Dark Lachris",
        image: "Ressource/Image/Personnages/DarkLachris.jpg",
        categorie: "Sith",
        espece: "Humain",
        sexe: "Féminin",
        statut: "Dark ",
        corps: "Lors du déclenchement de la Grande Guerre Galactique , une guerre qui opposa l'Empire Sith et la République Galactique, Lachris était un combattant talentueux du côté obscur et devint l'apprenti de Dark Marr , membre du Conseil Noir. Elle reçut finalement le titre de Dark et devint un puissant Seigneur Sith.En 3653 av.BY , Lachris faisait partie de la force d'invasion de l'Empire Sith qui attaqua Coruscant , la planète capitale de la République.Après le Traité de Coruscant , Dark Lachris prit Lerek Serrus comme premier apprenti pendant le conflit à l'échelle de la galaxie , connu sous le nom de Guerre froide , qui dura dix ans .Pendant la guerre, Dark Lachris et son apprenti menèrent leurs forces impériales sur Balmorra sous le règne du Conseil Noir. Après avoir exécuté son prédécesseur, elle s'est nommée commandant en chef local. C'est là que de nombreux Balmorrans formèrent une résistancepour attaquer Lachris et ses forces impériales.Alors que l'Empire Sith avait atteint le monde en cours en 3643 av.BY , Lachris décida de se rendre personnellement et de se rendre sur les terres plates de Sundari, où se trouvait la base de commandement avancée de l'Empire Sith. Elle fut informée que le Grand Maréchal Cheketta avait envoyé un certain nombre de renforts Jedi pour soutenir la résistance. Elle chargea une équipe d'intervention impériale de fermer les barricades de l' usine d'armes de Balmorran et de trouver des preuves solides de l'implication officielle de la République. Alors que les Impériaux parvenaient à infiltrer l'usine impériale et à vaincre le Jedi Ralon Nys ainsi que ses commandos de l'escouade Tempest, Lachris envoya les Impériaux rencontrer le Grand Maréchal. Alors que les derniers restes de la résistance formaient une armée, Lachris chargea l'équipe d'attaque impériale de briser la résistance restante. La mission réussit et Dark Lachris prit le contrôle du monde.",
    },
    {
        id: "9",
        title: "Vekarr",
        image: "Ressource/Image/Personnages/Vekarr.jpg",
        categorie: "Militaire ",
        espece: "Humain",
        sexe: "Masculin ",
        statut: "lieutenant ",
        corps: "Vekarr était un humain qui détenait le grade de lieutenant dans l' armée impériale de l' Empire Sith renaissant pendant la Guerre Galactique. En 3642 av.BY, il était en poste sur Balmorra et chargé de superviser la prison de Gorinth Brig .",
    },
    {
        id: "10",
        title: "Dark Baras",
        image: "Ressource/Image/Personnages/DarkBaras.jpg",
        categorie: "Sith  ",
        espece: "Humain",
        sexe: "Masculin ",
        statut: "Dark  ",
        corps: "Dark Baras était un Seigneur Sith qui mena les négociations sur Alderaan en 3653 av.BY. Il usa du sac de Coruscant et de la prise en otage celle-ci (plan créé par l'Empereur Sith lui-même), il en résultat de la prise de nombreux systèmes stellaires périphériques de la République Galactique pour l'Empire en échange du quel ils redonnèrent Coruscant à la République. En 3643 av.BY, il se rendit sur Korriban afin de se trouver un nouvel apprenti. Il remarqua de nombreux apprentis comme Klemral, Vemrin ou la future Furie de l'Empereur. Dark Baras fût vaincu par son propre apprenti, la Furie de l'Empereur, sous les yeux du Conseil Noir et quoi que ce dernier eut décidé, plus personne n'entendit parler de Baras.",
    },
    {
        id: "11",
        title: "Rajivari",
        image: "Ressource/Image/Personnages/Rajivari.jpg",
        categorie: "Je'daii  ",
        espece: "Humain",
        sexe: "Masculin ",
        statut: "Maître",
        corps: "Rajivari était autrefois considéré comme le Maître Je'daii le plus sage de l'Ordre Je'daii. Reconnu pour ses talents en tant que leader et sa sagesse, le Je'daii guida les armées de l'Ordre durant la Guerre de la Reine-Despote. Durant cette guerre il gagna de très nombreuses batailles, mais à la fin de cette dernière, Rajivari décida des déposer les armes et de vivre dans l'isolation sur l'une des îles qui encerclaient le Temple de Akar Kesh pour méditer sur la Force. Un de ces anciens apprentis, Ketu, qui était devenu le maître du temple, lui rendait parfois visite pour trouver conseil sur les questions importantes de l'Ordre Je'daii. En 25800 av.BY, Ketu expliqua les sombres visons que Daegen Lok avait vu dans les profondeurs du Gouffre, prédisant l'arrivé d'une armée menée par un individu avec un œil rouge armé d'une épée de feu. Sept ans plus tard, Rajivari fut à nouveau visité par Ketu, venu pour apprendre à son ancien maître les nouvelles visons des trois Voyageurs Je'daii Sek'nos Rath, Tasha Ryo et Shae Koda sur l'arrivée de Xesh. Rajivari, en désaccord avec la décision du maître de ne pas considérer la vision de Lok, utilisa de sa sagesse pour apprendre à Ketu qu'un étranger avait exilé sur Bogan, indiquant que \"Là où il y a un guerrier, une armée peut suivre\". Plus tard, Ketu demanda à son ancien maître de l'aider à accéder à l'Holocron Kwa, une relique d'une civilisation éteinte. Après la dissolution de l'Ordre Je'daii et la création de l'Ordre Jedi, Rajivari fut un des premiers membres du Conseil Jedi, mais il n'appréciait guère les règles du nouvel Ordre ainsi que leurs politiques et leurs faiblesses. Il commença alors à rassembler des adeptes qui le suivraient sur la voix du Côté Obscur de la Force. Rajivari débuta son insurrection pour faire tomber l'Ordre, mais rien ne se passa comme prévu, les insurgés furent très vite repoussés jusqu'à la ville antique de Kaleth où ils se mirent à l'abri temporairement. Tout les espoirs de victoire de Rajivari furent brisé, et lors du siège, ses derniers disciples se firent massacrer alors qu'eux, dans leur fanatisme, croyaient encore à la victoire. Ainsi à la fin du siège, Rajivari mourut.",
    },
    {
        id: "12",
        title: "Miarta Sek",
        image: "Ressource/Image/Personnages/MiartaSek.jpg",
        categorie: "Je'daii  ",
        espece: "Sith",
        sexe: "Féminin ",
        statut: "Maître",
        corps: "Sith sensible à la Force , Miarta Sek est née dans le clan Sek qui a accepté qu'elle soit entraînée aux voies de la Force par l' Ordre Je'daii sur la planète Tython , l'une des neuf planètes du système Tython qui constituait les colonies établies. Des mondes . Guérisseur formé du Grand Temple de Mahara Kesh , Sek reçut le titre de Maître du Temple Je'daii et supervisa les opérations du Temple des Compétences de la Force, Qigong Kesh . La grand-mère maternelle du Voyageur Je'daii Sek'nos Rath , Sek et les autres Maîtres du Temple formèrent le Conseil Je'daii , se réunissant par holocommunication au Temple de l'Équilibre, Akar Kesh .",
    },
    {
        id: "13",
        title: "Jake Fenn",
        image: "Ressource/Image/Personnages/JakeFenn.jpg",
        categorie: "Je'daii  ",
        espece: "Humain ",
        sexe: "Masculin  ",
        statut: "Maître",
        corps: "Humain sensible à la Force, Jake Fenn rejoignit l'Ordre Je'daii pour y apprendre à maîtriser ce flux. Etant né dans une famille d'êtres ayant des affinités particulières avec la Force – sa sœur Rori Fenn étant elle-même une Ranger Je'daii – Jake Fenn fut nommé Maître de Temple de Bodhi, le Grand Temple des Arts, quelques années avant[4] la Guerre de la Reine-Despote. En tant que Maître de Temple, Fenn faisait partie du Conseil Je'daii qui se rassemblait par holocommunication à Akar Kesh, le Temple de l’Équilibre. Ami du Maître Je'daii Brock, le fils de ce dernier, Dalien, suspectait Jake Fenn de louer les œuvres de son père uniquementparce qu'il avait du respect pour lui et non pour son talent. Des années plus tard, Jake Fenn participa au rassemblement du Conseil Je'daii lorsque le Dévoreur, un vaisseau Rakata, s'écrasa sur Tython en causant une immense tempête de Force. Entrant en profonde méditation avec les autres Maîtres de Temple,ils parvinrent tous ensemble à disperser la tempête et à sauver leur planète d'une destruction certaine. Par la suite, Fenn, sa sœur Rori, la Ranger Bel Zana et le Voyageur Je'daii Sek'nos Rath furent chargés de retrouver le Limier de Force Xesh et l'exilé Daegen Lok qui s'étaient enfuis de leur prison sur Bogan. Ils les traquèrent jusque sur Krev Cœur où ils les attaquèrent dans les mines de cristaux de la planète. Affrontant Lok, Fenn perçut l'arrogance de son ennemi à travers lui mais ce dernier le fit alors tomber après lui avoir donné un violent coup dans le torse. Lok profita de cet instant pour s'immerger dans l'esprit de Fenn et y découvrit que le Maître de Temple avait des sentiments pour la Ranger Bel Zana. Se servant de cette information, Lok projeta Zana par dessus la falaise et Sek'nos Rath se sacrifia pour la sauver, laissant le temps à Lok et Xesh de s'enfuir. Par la suite, Fenn amena Zana dans un centre médical sur Kalimahr et contacta les autres Je'daii pour les informer de l'état de Zana et de la plausible mort de Rath qui avait chuté de la falaise pour sauver Zana. Lorsque l'Empire Infini envahit le système Tython, Jake Fenn servait en tant que général au sein des forces Je'daii et combattit les Rakata afin de les empêcher de s'emparer des Mondes Colonisés.",
    },
    
]

bestiaire = [
    {

    },
]

resumer = [
    {

    },
]